### ISSUE TITLE
describe measurement plan

### ISSUE THREAD

**Issue by joeclark-phd** [asu-cis-capstone/rustyrhino#24]

**Comment by crayn3** [comment]
Hello Joe, I upload an image but It wasn't included in the readme.md. I
embedded it now. Is this OK? Thanks, Chris.
https://u2167478.ct.sendgrid.net/wf/click?upn=XnXXkQ-2FjYK0B1cRlhxo0x7swf8Vjpjf7hdEikUAZaihYdsjF5GZtgYnFFnF5qxsiIK40k-2FJ5zTponX-2FnC5U1j-2F057mZ3ZDNSB-2B2JQ-2FkGnDU-3D_s5UH8bhnBaopYjthcNSRcRUZLMySdogNweS2Xs5olhUo4J7IKUxLIrtOi-2F3l-2F73Ocab0Ifr8apBxddcwZYsM32RGWjrT6aZGNVYoAehrbem3Q1uXKlogTBVPJGI7KnEdOihlrlujvUNlv0mIVVJjr-2FBMrnNnOh5TAK4U3popCtI-2FuEcH5qtcgW7MdXAn324J6cZFAxwVhQcYA43e0YZLaJjty8lHGgxQjSzjikv8ZFVo-2BlBRi-2FWNxgS6kgckY4GVu70jMC8j0yVadzhZ4wUAHSW-2FMfg3UlC8fF1btNn-2BblsMaOTl3vMElsHPWKae5tOtIXR6SuT02ubvZJSNY7zyNA-3D-3D
